name: fm-github-actions-test
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  - push
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
